env:
  global:
    - secure: "hrrDBtiAms/sX+66NMKx0WFaPexuPlwVJ5mmtv8Hq9DPP3cOureO7RjTgnOKEdwYO/syrG/2UBcQCLFfm/UPkjJIwDAqqzavqcHdt82px/SH/X4kdbKGbIIE1TOWKchRuIvDGQT1itfR5L2lafgchYefi+p5GdxUKLSsu9QICgC4xJZ6LgW2dl18mStTH5sjxmhFxiqMnHEA/Xq5J+zprmfEaTWG5wLL6t2fiLCQLejW9+r/HSBgDlAC4g5X6Urfyj3UxW9QFGA1QS4+vL1f6JxTmhu6j9Oct6moGwe/6nSX73knx2sDLUEolqG07Q2yxw290KZKfBZ8lUUdvMy7dOQXVUxpaH3/+J5RTowEHTRbMAPX2VPW9yeXYa/L2DHNII/y6apV6QVEzwHvWp6SOEFvPkMDXOYfZF0qD9+ro6+g86yjkhEH80xjpQYpdfkezU8CLrcuzz96fMroeCBZ+JJg6+tAaG4waHJcVxoP8XFxPUyfHTWx8cFYp1gnjkHVPacZuJ9pN2b4pD1QPYmgJsd6J/4dtNYveKXsXU7wsG8StpqMcSu8MNnhzJiOIuerzJT3BaA4Pfl4jlyGMX8QNhc7oD49mGkD3T9Q8anjPeDjnaFiC++BczC8mMFx0NiSZoNmhQXpn0cKb7aKn5OSjqzBv7k6C3tUfltATgrakwM="

script:
  - sonar-scanner

before_install:
  - curl -F "period=5000" -F "color=#AB00FF" "https://api.cilamp.se/v1/${BI_BEACON_SYSTEM_ID}/"

before_script:
  - curl -F "period=5000" -F "color=#0000FF" "https://api.cilamp.se/v1/${BI_BEACON_SYSTEM_ID}/"

after_success:
  - dist/publish-artifacts.sh
  - curl -F "color=#00FF00" "https://api.cilamp.se/v1/${BI_BEACON_SYSTEM_ID}/"

after_failure:
  - curl -F "color=#FF0000" "https://api.cilamp.se/v1/${BI_BEACON_SYSTEM_ID}/"
